_includes/footer.html
=> Correct jquery path

_posts/2015-01-11-hacking-github.md
A list of some simple apps that augment GitHub's web interface to provide non-GitHub users with features that lower the barrier to entry.
=> Hacking GitHub: 12 simple tools that help non-GitHub users level up their GitHub game

_posts/2015-01-11-hacking-github.md
=> Some minor fixes to github tools post

_posts/2015-01-11-hacking-github.md
Wow! Great work with this post :+1: 
Centralizing these resources will be amazingly helpful when working with non-github users.
I've fixed a quick spelling error in the word "Microsoft" with this pull request.
Thankyou,
psgs :palm_tree:
=> Improve "Microsoft" spelling

_posts/2015-01-26-the-fine-print-nobody-reads.md
Read out from the collaborate panel
=> Post on fed-friendly TOSs

_posts/2015-02-06-word-diff.md
Great post!
One minor critique: it seems very manual right now, diminishing the value prop. The process, as I understand it, is:
1. Receive a word doc from someone
2. Put it in my repo, commit, push, create a PR
3. Make sure the changes look good and merge
4. Send feedback via email to the client.
This seems to make it only nice for the internal group, only really offering GitHub PR-like collaboration for the team evaluating the response. It's also a Word-based editing experience as well, so I can't use Markdown. (running contrary to this line in the post: `More importantly, you can collaborate using the simple tools you love like Markdown and Git...`).
I can't wait to see how it grows! I think rewording the `When would you use this?` paragraph to be more specific to intra-team …
=> Minor typos

_posts/2015-02-06-word-diff.md
Not much to see here, just a couple of typo fixes.
=> Fixes some typos in the Word Diff article

_posts/2014-12-17-the-myth-of-government-it.md
I really appreciate the work you're doing around Open Government.
Thank you, it's very refreshing!
I work for a Ca. State Agency in IT & I am also an Open Source developer.
I'd really like to speak with you about some opportunities I feel GitHub could benefit from with the State Civic space. If you are interested in speaking with me about these opportunities feel free to [email me](mailto:zach.moreno@coastal.ca.gov).
=> fixed minor word order

_posts/2015-02-16-jekyll-collections.md
Fixes #207.
@parkr still WIP, but thoughts?
=> ELI5: Jekyll Collections

_posts/2015-04-27-eight-lessons-learned-hacking-on-github-pages-for-six-months.md
Ridiculously excited/ashamed that this actually worked.
/cc @parkr
=> Add Pages post

_config.yml, _includes/improve.html
Just a modification of your code I will probably be using, so that I just edit the config.yml to and use the same contribution code, and link to GitHub to promote other projects for the curious visitors...
=> Contribute / improve post modification

_posts/2015-06-03-copyright-notices-for-websites-and-open-source-projects.md
You don't need a notice to obtain copyright, but there are other reasons to give a copyright notice, so identify them.  Also remark that notices are easy to add.
=> Identify OTHER reasons for a copyright notice

_posts/2015-07-20-write-corporate-blog-posts-as-a-human.md
you might not care less about this PR.
=> typo on could not care less

_posts/2015-02-20-jekyll-collections.md
=> Typo: Content Mangament System -> Content Management System

_posts/2015-08-12-the-zen-of-github.md
I'd like to quote this sentence on Twitter :)
=> Typo fix in 2015-08-12-the-zen-of-github.md

_posts/2015-09-13-github-pages-edit-button.md
Fixes https://github.com/benbalter/benbalter.github.com/issues/285.
=> Improve this content button post

_posts/2015-09-21-open-source-behind-the-firewall.md
How open source workflows and philosophies can be leveraged by the enterprise to produce more modern software, even if that software ultimately remains closed source.
=> Open source behind the firewall

_posts/2015-03-08-open-source-best-practices-internal-collaboration.md
Seems like one of the uses of "outside" in this sentence needs to be "inside"
=> Wording fix

_posts/2015-05-22-test-your-prose.md
You may also want to consider converting the remaining two commas in this sentence to em dashes
=> Remove unnecessary commas

_posts/2013-06-26-how-to-convert-shapefiles-to-geojson-for-use-on-github.md
Embedded map of embassies is currently broken because the geojson files were moved from master/ to master/maps/
=> Fix embedded map

_posts/2012-10-19-we-ve-been-trained-to-make-paper.md
(Note: Nothing changed on line 61... so I'm not sure why that's showing up with it being replaced by itself.)
=> Fix grammar/punctuation

_posts/2015-12-08-types-of-pull-requests.md
Fix spelling in line 35 'memebers' --> 'members'
=> Typo fix line 35

_posts/2015-11-23-why-open-source.md
I was looking for the reference / [link to this post](http://ben.balter.com/2015/11/23/why-open-source/) and noticed when I did that the table was mis-formatted... Maybe this is a Jekyll 2 -> 3 issue?
Anyways, I fixed the table rendering (looks ok in GitHub browser preview) to correct the issue. It looks like GitHub markdown previews don't support the `{: .table style="..."}` formatting though, so I'm not 100% that will look correct after the update. It renders incorrectly in [GitHub](https://github.com/benbalter/benbalter.github.com/blob/master/_posts/2015-11-23-why-open-source.md), but maybe it'll be fine when [Pages / Jekyll renders it](http://ben.balter.com/2015/11/23/why-open-source/)?
=> Fixed table formatting

_posts/2015-11-23-why-open-source.md
One more for good measure to try to fix issues with [Pages rendering](http://ben.balter.com/2015/11/23/why-open-source/)...
GitHub markdown preview was working ok, but Jekyll / Pages render was broken, inserting: `:heavy_check_mark:` raw.
=> More fixes to table

_includes/improve.html
"Help Improve article ___" >>> "Help improve article ___"
=> Use lowercase "i" in link title for the "Improve" link

_posts/2012-10-01-welcome-to-the-post-cms-world.md
=> Fix typo on 2012-10-01-welcome-to-the-post-cms-world.md

Gemfile, _config.yml, _data/books.yml, assets/css/style.scss, books-for-geeks.html
To move https://www.pinterest.com/benbalter/books-for-geeks/.
=> Create books for geeks page

_posts/2016-12-23-atom-for-prose.md
=> Fix broken link

_posts/2017-04-14-create-an-open-source-moderator-role-with-protected-branches-on-github.md
Fixes https://github.com/benbalter/benbalter.github.com/issues/423.
=> Using protected branches to empower non-code contributors on GitHub

_posts/2017-06-19-how-not-to-prioritize-a-feature.md
Made some tiny edits, all of which are noted.
=> Copy-edits

Rakefile, spec/amazon_link_check.rb
=> fix Rubocop offenses

_data/books.yml
Fixes https://github.com/benbalter/benbalter.github.com/issues/447 where book link 404s
=> Update ASIN for product management book

_posts/2015-01-26-the-fine-print-nobody-reads.md
* Fix broken links
* Use https where possible
* Centralize and de-duplicate links in footer link references to make it
easier to update links in future
=> Update links in "the fine print nobody reads" blog

_posts/2020-01-02-Resolutions.md, _posts/2020-01-02-resolutions-for-sustaining-and-growing-open-source-communities.md
-----
[View rendered _posts/2020-01-02-resolutions-for-sustaining-and-growing-open-source-communities.md](https://github.com/benbalter/benbalter.github.com/blob/resolutions-for-sustaining-and-growing-open-source-communities/_posts/2020-01-02-resolutions-for-sustaining-and-growing-open-source-communities.md)
=> Resolutions for sustaining and growing open source communities

_posts/2020-03-18-tips-for-working-remotely.md
-----
[View rendered _posts/2020-03-18-tips-for-working-remotely.md](https://github.com/benbalter/benbalter.github.com/blob/tips-for-working-remotely/_posts/2020-03-18-tips-for-working-remotely.md)
=> Tips for working remotely

_posts/2020-08-27-10-years.md, _posts/2020-09-12-10-years.md
The top 10 posts of the past 10 years
-----
[View rendered _posts/2020-09-12-10-years.md](https://github.com/benbalter/benbalter.github.com/blob/10-years/_posts/2020-09-12-10-years.md)
=> 10 years of ben.balter.com

_posts/2016-10-31-eight-things-i-wish-i-knew-my-first-week.md
-----
[View rendered _posts/2016-10-31-eight-things-i-wish-i-knew-my-first-week.md](https://github.com/benbalter/benbalter.github.com/blob/eight-things-i-wish-i-knew-my-first-week/_posts/2016-10-31-eight-things-i-wish-i-knew-my-first-week.md)
=> Back-post "Eight things I wish I knew my first week at GitHub" post

_posts/2014-11-06-rules-of-communicating-at-github.md
Like to http://giphy.com/gifs/puppies-cute-animals-asdfghjkl-6UZFwMYqCeXi8 is no longer available.
-----
[View rendered _posts/2014-11-06-rules-of-communicating-at-github.md](https://github.com/wilsonmar/benbalter.github.com/blob/patch-1/_posts/2014-11-06-rules-of-communicating-at-github.md)
=> Remove outdated URL

_posts/2021-12-15-github-actions-website-api-change-notification.md
null
-----
[View rendered _posts/2021-12-15-github-actions-website-api-change-notification.md](https://github.com/benbalter/benbalter.github.com/blob/github-actions-website-api-change-notification/_posts/2021-12-15-github-actions-website-api-change-notification.md)
=> GitHub actions website api change notification

_posts/2021-12-15-github-actions-website-api-change-notification.md
-----
[View rendered _posts/2021-12-15-github-actions-website-api-change-notification.md](https://github.com/parkr/benbalter.github.com/blob/patch-1/_posts/2021-12-15-github-actions-website-api-change-notification.md)
=> Add closing } for ${{ steps... }}

_posts/2022-01-31-leaders-show-their-work.md
null
-----
[View rendered _posts/2022-01-31-leaders-show-their-work.md](https://github.com/IanLee1521/benbalter.github.com/blob/patch-19/_posts/2022-01-31-leaders-show-their-work.md)
=> Fix minor typo

_posts/2014-11-06-rules-of-communicating-at-github.md
Change "Have two minute..." to "Have two minutes..." 
Hoping to honor the 1st item (Ship something in your first two weeks) in [Eight things I wish I knew my first week at GitHub](https://ben.balter.com/2016/10/31/eight-things-i-wish-i-knew-my-first-week-at-github/#1-ship-something-in-your-first-two-weeks) 👀 ❤️
=> Fix grammar to plural

_posts/2023-08-04-more-with-less.md, _posts/2023-08-04-remote-work-communicate-more-with-less.md
Fixes https://github.com/benbalter/benbalter.github.com/issues/647.
=> Remote work requires communicating more, less frequently
